repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*\.tsv|.*\.md
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: clang-tidy
        args: ["-p=build"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
        - "@commitlint/config-conventional"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    - id: hadolint-docker
