name: Release

on:
  push:
    branches:
      - master

  workflow_call:
    inputs:
      node-version:
        default: '16.15.1'
        description: Node runtime version
        required: false
        type: string
      python-version:
        default: '3.11'
        description: Python runtime version
        required: false
        type: string

jobs:
    quality:
        uses: ./.github/workflows/quality.yaml
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ inputs.node-version }}

    release:
        runs-on: ubuntu-latest
        needs:
          - quality
        timeout-minutes: 5
        name: Run release
        steps:
          - name: Checkout code so that it is available to use in the executing runner
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              token: ${{ secrets.PAT_GITHUB }}
          - name: Python Semantic Release
            uses: relekang/python-semantic-release@master
            with:
              github_token: ${{ secrets.PAT_GITHUB }}
